/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

import { motion } from "framer-motion-3d";
import { useCurrentSection } from "@/app/data/atoms";

type GLTFResult = GLTF & {
  nodes: {
    Circle001_Material002_0: THREE.Mesh;
    Circle001_Material002_0_1: THREE.Mesh;
    Circle001_Material002_0_2: THREE.Mesh;
    defaultMaterial: THREE.Mesh;
    defaultMaterial001: THREE.Mesh;
    Cube006_1: THREE.Mesh;
    Cube006_2: THREE.Mesh;
    Cube006_3: THREE.Mesh;
    Monitor: THREE.Mesh;
    Monitor_1: THREE.Mesh;
    Monitor_2: THREE.Mesh;
    Monitor_3: THREE.Mesh;
    Monitor_4: THREE.Mesh;
    Monitor_5: THREE.Mesh;
    Monitor_6: THREE.Mesh;
    Monitor_7: THREE.Mesh;
    Monitor_8: THREE.Mesh;
    Monitor_9: THREE.Mesh;
    Plane104: THREE.Mesh;
    Plane104_1: THREE.Mesh;
    Plane104_2: THREE.Mesh;
    Plane104_3: THREE.Mesh;
    ["4001"]: THREE.Mesh;
    ["4001_1"]: THREE.Mesh;
    ["4001_2"]: THREE.Mesh;
    ["4001_3"]: THREE.Mesh;
    Console: THREE.Mesh;
    Table: THREE.Mesh;
    Bulb_LP001: THREE.Mesh;
    Cable_LP001: THREE.Mesh;
    Lamp_Inside_L001: THREE.Mesh;
    Lamp_LP002: THREE.Mesh;
    Lamp_Stand_LP001: THREE.Mesh;
    Lamp_Stand_P_LP001: THREE.Mesh;
    NutsBolts_LP001: THREE.Mesh;
    Plastic_LP001: THREE.Mesh;
    Wood_LP001: THREE.Mesh;
    Mesh_4: THREE.Mesh;
    Mesh_5: THREE.Mesh;
    Mesh_6: THREE.Mesh;
    Mesh_7: THREE.Mesh;
    Mesh_10: THREE.Mesh;
    Mesh_11: THREE.Mesh;
    Mesh_12: THREE.Mesh;
    Mesh_13: THREE.Mesh;
    Mesh_16: THREE.Mesh;
    Mesh_17: THREE.Mesh;
    Mesh: THREE.Mesh;
    Mesh_1: THREE.Mesh;
    Mesh_18: THREE.Mesh;
    Mesh_19: THREE.Mesh;
    Mesh_20: THREE.Mesh;
    Mesh_21: THREE.Mesh;
    Mesh_2: THREE.Mesh;
    Mesh_3: THREE.Mesh;
    Mesh_24: THREE.Mesh;
    Mesh_25: THREE.Mesh;
    Mesh_26: THREE.Mesh;
    Mesh_27: THREE.Mesh;
    Mesh_8: THREE.Mesh;
    Mesh_9: THREE.Mesh;
    Mesh_28: THREE.Mesh;
    Mesh_29: THREE.Mesh;
    Mesh_30: THREE.Mesh;
    Mesh_31: THREE.Mesh;
    Mesh_14: THREE.Mesh;
    Mesh_15: THREE.Mesh;
    Mesh_32: THREE.Mesh;
    Mesh_33: THREE.Mesh;
    Mesh_34: THREE.Mesh;
    Mesh_35: THREE.Mesh;
    Mesh_22: THREE.Mesh;
    Mesh_23: THREE.Mesh;
    Cube019: THREE.Mesh;
    Cube023: THREE.Mesh;
    Cube024: THREE.Mesh;
    Cylinder: THREE.Mesh;
    Cylinder009: THREE.Mesh;
    Cube020_1: THREE.Mesh;
    Cube020_2: THREE.Mesh;
    Cube021_1: THREE.Mesh;
    Cube021_2: THREE.Mesh;
    Cube018_1: THREE.Mesh;
    Cube018_2: THREE.Mesh;
    Cube028: THREE.Mesh;
    Cube028_1: THREE.Mesh;
    Cube015_1: THREE.Mesh;
    Cube015_2: THREE.Mesh;
    Cube014_1: THREE.Mesh;
    Cube014_2: THREE.Mesh;
    Cube013_1: THREE.Mesh;
    Cube013_2: THREE.Mesh;
    body: THREE.Mesh;
    marks: THREE.Mesh;
    metal: THREE.Mesh;
    Circle_1: THREE.Mesh;
    Circle_2: THREE.Mesh;
    IVY_Curve004: THREE.Mesh;
    Plane005: THREE.Mesh;
    Circle002: THREE.Mesh;
    Circle043: THREE.Mesh;
    Circle043_1: THREE.Mesh;
    Circle043_2: THREE.Mesh;
    Circle006: THREE.Mesh;
    Circle007: THREE.Mesh;
    Circle018: THREE.Mesh;
    Circle019: THREE.Mesh;
    Circle048: THREE.Mesh;
    Circle049: THREE.Mesh;
    Cube007_1: THREE.Mesh;
    Cube007_2: THREE.Mesh;
    Cube007_3: THREE.Mesh;
    Cube005_1: THREE.Mesh;
    Cube005_2: THREE.Mesh;
    Cube1403: THREE.Mesh;
    Cube1404: THREE.Mesh;
    Cube1405: THREE.Mesh;
    Cube1406: THREE.Mesh;
    Cube1407: THREE.Mesh;
    Cube1408: THREE.Mesh;
    NurbsCurve: THREE.Mesh;
    Cube011_1_instance_0: THREE.Mesh;
    Cube1410: THREE.Mesh;
    Cube1411: THREE.Mesh;
    Cube1412: THREE.Mesh;
    Cube1413: THREE.Mesh;
    Cube1414: THREE.Mesh;
    Cube1415: THREE.Mesh;
    Cube011_1_instance_1: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cube004: THREE.Mesh;
    Cube005: THREE.Mesh;
    Cube006: THREE.Mesh;
    Cube007: THREE.Mesh;
    Cube011_1_instance_2: THREE.Mesh;
    Cube009: THREE.Mesh;
    Cube010: THREE.Mesh;
    Cube011: THREE.Mesh;
    Cube012: THREE.Mesh;
    Cube013: THREE.Mesh;
    Cube014: THREE.Mesh;
    NurbsCurve001: THREE.Mesh;
    Cube048: THREE.Mesh;
    Computer: THREE.Mesh;
    Plane: THREE.Mesh;
    Plane_1: THREE.Mesh;
    Black_keys_1: THREE.Mesh;
    Black_keys_2: THREE.Mesh;
    Black_keys_3: THREE.Mesh;
    Black_keys_4: THREE.Mesh;
    Cube033: THREE.Mesh;
    White_keys: THREE.Mesh;
    Cube035_1: THREE.Mesh;
    Cube035_2: THREE.Mesh;
    Cube035_3: THREE.Mesh;
    Cube035_4: THREE.Mesh;
    Cube035_5: THREE.Mesh;
  };
  materials: {
    ["Material.004"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    DefaultMaterial: THREE.MeshStandardMaterial;
    ["mouse body"]: THREE.MeshStandardMaterial;
    ["0,0,0"]: THREE.MeshPhysicalMaterial;
    ["191,191,191"]: THREE.MeshPhysicalMaterial;
    ["5,5,5"]: THREE.MeshPhysicalMaterial;
    ["60,59,59"]: THREE.MeshPhysicalMaterial;
    ["Material.008"]: THREE.MeshStandardMaterial;
    ["Material.009"]: THREE.MeshStandardMaterial;
    ["Material.010"]: THREE.MeshStandardMaterial;
    stem: THREE.MeshStandardMaterial;
    glass: THREE.MeshPhysicalMaterial;
    Leaf: THREE.MeshStandardMaterial;
    ["White murble"]: THREE.MeshStandardMaterial;
    ["Lamp_LP.002_BAKED.002"]: THREE.MeshStandardMaterial;
    ["book cover.001"]: THREE.MeshStandardMaterial;
    ["stacked paper.001"]: THREE.MeshStandardMaterial;
    ["book cover.001"]: THREE.MeshStandardMaterial;
    ["stacked paper.001"]: THREE.MeshStandardMaterial;
    Bookshelf_aluminum: THREE.MeshStandardMaterial;
    heater_black: THREE.MeshStandardMaterial;
    Plant_Pot: THREE.MeshStandardMaterial;
    Plant_Stem: THREE.MeshStandardMaterial;
    Plant_Leaf: THREE.MeshStandardMaterial;
    BlackPlastic: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
    BlackLeazer: THREE.MeshStandardMaterial;
    Metal: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    wood: THREE.MeshStandardMaterial;
    stainless: THREE.MeshPhysicalMaterial;
    black: THREE.MeshPhysicalMaterial;
    ["Iron Touched"]: THREE.MeshStandardMaterial;
    ["plastic touched"]: THREE.MeshStandardMaterial;
    ["Brass polished"]: THREE.MeshStandardMaterial;
    ["black rubber.002"]: THREE.MeshStandardMaterial;
    ["White murble"]: THREE.MeshStandardMaterial;
    ["White Wall 02-Freepoly.org"]: THREE.MeshPhysicalMaterial;
    ["Black Keys"]: THREE.MeshStandardMaterial;
    ["Black case"]: THREE.MeshStandardMaterial;
    ["White keys"]: THREE.MeshStandardMaterial;
    ["Red case"]: THREE.MeshStandardMaterial;
    ["LED red"]: THREE.MeshStandardMaterial;
    ["Metal Switch"]: THREE.MeshStandardMaterial;
    ["LED white"]: THREE.MeshStandardMaterial;
  };
};

export function Studio(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/studio.glb") as GLTFResult;
  const [currentSection] = useCurrentSection();
  return (
    <group
      {...props}
      dispose={null}
      position={[1.9, -3.05, -2]}
      rotation-y={-Math.PI / 2}
    >
      <motion.group
        initial={{ scale: 0 }}
        animate={currentSection === 0 ? { scale: 1 } : { scale: 0 }}
      >
        <group name="Chair" position={[1.977, 1.158, 0.257]} scale={0.658}>
          <mesh
            name="Circle001_Material002_0"
            castShadow
            receiveShadow
            geometry={nodes.Circle001_Material002_0.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            name="Circle001_Material002_0_1"
            castShadow
            receiveShadow
            geometry={nodes.Circle001_Material002_0_1.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            name="Circle001_Material002_0_2"
            castShadow
            receiveShadow
            geometry={nodes.Circle001_Material002_0_2.geometry}
            material={materials["Material.003"]}
          />
        </group>
        <group name="Mouse" position={[2.684, 1.238, 0.444]} scale={0.085}>
          <mesh
            name="Cube006_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube006_1.geometry}
            material={materials["mouse body"]}
          />
          <mesh
            name="Cube006_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube006_2.geometry}
            material={materials["mouse body"]}
          />
          <mesh
            name="Cube006_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube006_3.geometry}
            material={materials["mouse body"]}
          />
        </group>
        <group name="Monitor_" position={[3.084, 1.467, 0.283]} scale={0.727}>
          <mesh
            name="Monitor"
            castShadow
            receiveShadow
            geometry={nodes.Monitor.geometry}
            material={materials["0,0,0"]}
          />
          <mesh
            name="Monitor_1"
            castShadow
            receiveShadow
            geometry={nodes.Monitor_1.geometry}
            material={materials["191,191,191"]}
          />
          <mesh
            name="Monitor_2"
            castShadow
            receiveShadow
            geometry={nodes.Monitor_2.geometry}
            material={materials["0,0,0"]}
          />
          <mesh
            name="Monitor_3"
            castShadow
            receiveShadow
            geometry={nodes.Monitor_3.geometry}
            material={materials["5,5,5"]}
          />
          <mesh
            name="Monitor_4"
            castShadow
            receiveShadow
            geometry={nodes.Monitor_4.geometry}
            material={materials["60,59,59"]}
          />
          <mesh
            name="Monitor_5"
            castShadow
            receiveShadow
            geometry={nodes.Monitor_5.geometry}
            material={materials["0,0,0"]}
          />
          <mesh
            name="Monitor_6"
            castShadow
            receiveShadow
            geometry={nodes.Monitor_6.geometry}
            material={materials["191,191,191"]}
          />
          <mesh
            name="Monitor_7"
            castShadow
            receiveShadow
            geometry={nodes.Monitor_7.geometry}
            material={materials["0,0,0"]}
          />
          <mesh
            name="Monitor_8"
            castShadow
            receiveShadow
            geometry={nodes.Monitor_8.geometry}
            material={materials["5,5,5"]}
          />
          <mesh
            name="Monitor_9"
            castShadow
            receiveShadow
            geometry={nodes.Monitor_9.geometry}
            material={materials["60,59,59"]}
          />
        </group>
        <group name="Keyboard" position={[2.717, 1.215, 0.107]} scale={0.267}>
          <mesh
            name="Plane104"
            castShadow
            receiveShadow
            geometry={nodes.Plane104.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            name="Plane104_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane104_1.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            name="Plane104_2"
            castShadow
            receiveShadow
            geometry={nodes.Plane104_2.geometry}
            material={nodes.Plane104_2.material}
          />
          <mesh
            name="Plane104_3"
            castShadow
            receiveShadow
            geometry={nodes.Plane104_3.geometry}
            material={materials["Material.010"]}
          />
        </group>
        <group name="PlantOnDesk" position={[3.16, 1.412, 1.908]} scale={0.223}>
          <mesh
            name="4001"
            castShadow
            receiveShadow
            geometry={nodes["4001"].geometry}
            material={materials.stem}
          />
          <mesh
            name="4001_1"
            castShadow
            receiveShadow
            geometry={nodes["4001_1"].geometry}
            material={materials.stem}
          />
          <mesh
            name="4001_2"
            castShadow
            receiveShadow
            geometry={nodes["4001_2"].geometry}
            material={materials.glass}
          />
          <mesh
            name="4001_3"
            castShadow
            receiveShadow
            geometry={nodes["4001_3"].geometry}
            material={materials.Leaf}
          />
        </group>
        <mesh
          name="Console"
          castShadow
          receiveShadow
          geometry={nodes.Console.geometry}
          material={materials["White murble"]}
          position={[2.101, 1.869, -4.395]}
          scale={0.563}
        />
        <mesh
          name="Table"
          castShadow
          receiveShadow
          geometry={nodes.Table.geometry}
          material={materials["White murble"]}
          position={[2.229, 0.856, 0.583]}
          scale={1.644}
        />
        <mesh
          name="Computer"
          castShadow
          receiveShadow
          geometry={nodes.Computer.geometry}
          material={materials["White murble"]}
          position={[3.157, 0.722, 1.526]}
          scale={0.222}
        />
        <group name="House" position={[1.842, 2, 0]} scale={5}>
          <mesh
            name="Plane"
            castShadow
            receiveShadow
            geometry={nodes.Plane.geometry}
            material={materials["White Wall 02-Freepoly.org"]}
          />
          <mesh
            name="Plane_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane_1.geometry}
            material={materials["White murble"]}
          />
        </group>
        <mesh
          name="defaultMaterial"
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial.geometry}
          material={materials.DefaultMaterial}
          position={[3.151, 1.346, 1.19]}
          scale={0.137}
        />
        <mesh
          name="defaultMaterial001"
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial001.geometry}
          material={materials.DefaultMaterial}
          position={[3.172, 1.346, -0.57]}
          scale={0.137}
        />
        <mesh
          name="Bulb_LP001"
          castShadow
          receiveShadow
          geometry={nodes.Bulb_LP001.geometry}
          material={materials["White murble"]}
          position={[2.732, 1.543, 1.44]}
          scale={0.039}
        />
        <mesh
          name="Cable_LP001"
          castShadow
          receiveShadow
          geometry={nodes.Cable_LP001.geometry}
          material={materials["White murble"]}
          position={[2.728, 1.455, 1.558]}
          scale={0.208}
        />
        <mesh
          name="Lamp_Inside_L001"
          castShadow
          receiveShadow
          geometry={nodes.Lamp_Inside_L001.geometry}
          material={materials.DefaultMaterial}
          position={[2.73, 1.564, 1.438]}
          scale={0.077}
        />
        <mesh
          name="Lamp_LP002"
          castShadow
          receiveShadow
          geometry={nodes.Lamp_LP002.geometry}
          material={materials["Lamp_LP.002_BAKED.002"]}
          position={[2.73, 1.565, 1.439]}
          scale={0.077}
        />
        <mesh
          name="Lamp_Stand_LP001"
          castShadow
          receiveShadow
          geometry={nodes.Lamp_Stand_LP001.geometry}
          material={materials.DefaultMaterial}
          position={[2.73, 1.239, 1.534]}
          scale={0.076}
        />
        <mesh
          name="Lamp_Stand_P_LP001"
          castShadow
          receiveShadow
          geometry={nodes.Lamp_Stand_P_LP001.geometry}
          material={materials["White murble"]}
          position={[2.73, 1.434, 1.549]}
          scale={0.181}
        />
        <mesh
          name="NutsBolts_LP001"
          castShadow
          receiveShadow
          geometry={nodes.NutsBolts_LP001.geometry}
          material={materials.DefaultMaterial}
          position={[2.727, 1.453, 1.569]}
          scale={0.193}
        />
        <mesh
          name="Plastic_LP001"
          castShadow
          receiveShadow
          geometry={nodes.Plastic_LP001.geometry}
          material={materials["White murble"]}
          position={[2.732, 1.603, 1.459]}
          scale={0.034}
        />
        <mesh
          name="Wood_LP001"
          castShadow
          receiveShadow
          geometry={nodes.Wood_LP001.geometry}
          material={materials["White murble"]}
          position={[2.73, 1.434, 1.586]}
          scale={0.181}
        />
        <group name="Cube034" position={[-1.089, 0.839, -1.308]} scale={0.167}>
          <mesh
            name="Mesh_4"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_4.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            name="Mesh_5"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_5.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group name="Cube035" position={[-1.074, 0.853, -1.202]} scale={0.179}>
          <mesh
            name="Mesh_6"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_6.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            name="Mesh_7"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_7.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group name="Cube036" position={[-1.065, 0.854, -1.175]} scale={0.181}>
          <mesh
            name="Mesh_10"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_10.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            name="Mesh_11"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_11.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group name="Cube037" position={[-1.057, 0.83, -1.158]} scale={0.157}>
          <mesh
            name="Mesh_12"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_12.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            name="Mesh_13"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_13.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group name="Cube038" position={[-1.071, 0.857, -1.238]} scale={0.183}>
          <mesh
            name="Mesh_16"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_16.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            name="Mesh_17"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_17.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group name="Cube039" position={[-1.082, 0.849, -1.268]} scale={0.177}>
          <mesh
            name="Mesh"
            castShadow
            receiveShadow
            geometry={nodes.Mesh.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            name="Mesh_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_1.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group name="Cube040" position={[-1.065, 0.862, -1.098]} scale={0.189}>
          <mesh
            name="Mesh_18"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_18.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            name="Mesh_19"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_19.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group name="Cube041" position={[-1.056, 0.861, -1.037]} scale={0.188}>
          <mesh
            name="Mesh_20"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_20.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            name="Mesh_21"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_21.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group name="Cube042" position={[-1.06, 0.857, -1.064]} scale={0.184}>
          <mesh
            name="Mesh_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_2.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            name="Mesh_3"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_3.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group name="Cube067" position={[-1.059, 2.577, -1.055]} scale={0.184}>
          <mesh
            name="Mesh_24"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_24.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            name="Mesh_25"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_25.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group name="Cube068" position={[-1.056, 2.581, -1.027]} scale={0.188}>
          <mesh
            name="Mesh_26"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_26.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            name="Mesh_27"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_27.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          name="Cube069"
          position={[-1.065, 2.582, -1.089]}
          rotation={[1.755, -0.015, -0.078]}
          scale={0.19}
        >
          <mesh
            name="Mesh_8"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_8.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            name="Mesh_9"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_9.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group name="Cube070" position={[-1.081, 2.569, -1.258]} scale={0.177}>
          <mesh
            name="Mesh_28"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_28.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            name="Mesh_29"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_29.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          name="Cube071"
          position={[-1.071, 2.577, -1.229]}
          rotation={[1.909, -0.026, -0.076]}
          scale={0.19}
        >
          <mesh
            name="Mesh_30"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_30.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            name="Mesh_31"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_31.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group name="Cube072" position={[-1.056, 2.55, -1.149]} scale={0.157}>
          <mesh
            name="Mesh_14"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_14.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            name="Mesh_15"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_15.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group name="Cube073" position={[-1.065, 2.573, -1.166]} scale={0.181}>
          <mesh
            name="Mesh_32"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_32.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            name="Mesh_33"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_33.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group name="Cube074" position={[-1.073, 2.573, -1.193]} scale={0.179}>
          <mesh
            name="Mesh_34"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_34.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            name="Mesh_35"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_35.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group name="Cube075" position={[-1.088, 2.559, -1.299]} scale={0.167}>
          <mesh
            name="Mesh_22"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_22.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            name="Mesh_23"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_23.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <mesh
          name="Cube019"
          castShadow
          receiveShadow
          geometry={nodes.Cube019.geometry}
          material={materials["Lamp_LP.002_BAKED.002"]}
          position={[-1.09, 1.72, -1.375]}
          scale={1.234}
        />
        <mesh
          name="Cube023"
          castShadow
          receiveShadow
          geometry={nodes.Cube023.geometry}
          material={materials["Lamp_LP.002_BAKED.002"]}
          position={[-1.09, 1.634, -1.402]}
          scale={0.248}
        />
        <mesh
          name="Cube024"
          castShadow
          receiveShadow
          geometry={nodes.Cube024.geometry}
          material={materials["White murble"]}
          position={[-1.09, 1.727, -1.4]}
          scale={1.241}
        />
        <mesh
          name="Cylinder"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={nodes.Cylinder.material}
          position={[-1.091, 1.784, -1.375]}
          scale={1.153}
        />
        <mesh
          name="Cylinder009"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009.geometry}
          material={materials.Bookshelf_aluminum}
          position={[-1.091, 1.783, -1.375]}
          scale={1.151}
        />
        <group name="Cube015" position={[2.321, 1.233, 1.643]} scale={0.188}>
          <mesh
            name="Cube020_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube020_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            name="Cube020_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube020_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group name="Cube016" position={[2.3, 1.266, 1.643]} scale={0.179}>
          <mesh
            name="Cube021_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube021_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            name="Cube021_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube021_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group name="Cube017" position={[2.278, 1.324, 1.646]} scale={0.184}>
          <mesh
            name="Cube018_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube018_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            name="Cube018_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube018_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group name="Cube018" position={[2.268, 1.352, 1.65]} scale={0.182}>
          <mesh
            name="Cube028"
            castShadow
            receiveShadow
            geometry={nodes.Cube028.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            name="Cube028_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube028_1.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group name="Cube020" position={[2.328, 1.221, 1.641]} scale={0.19}>
          <mesh
            name="Cube015_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube015_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            name="Cube015_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube015_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group name="Cube021" position={[2.284, 1.295, 1.645]} scale={0.186}>
          <mesh
            name="Cube014_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube014_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            name="Cube014_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube014_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group name="Cube022" position={[2.322, 1.25, 1.622]} scale={0.174}>
          <mesh
            name="Cube013_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube013_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            name="Cube013_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube013_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <mesh
          name="body"
          castShadow
          receiveShadow
          geometry={nodes.body.geometry}
          material={materials.DefaultMaterial}
          position={[2.108, 1.25, -4.396]}
          scale={0.527}
        />
        <mesh
          name="marks"
          castShadow
          receiveShadow
          geometry={nodes.marks.geometry}
          material={materials.heater_black}
          position={[1.573, 1.094, -4.39]}
          scale={0.048}
        />
        <mesh
          name="metal"
          castShadow
          receiveShadow
          geometry={nodes.metal.geometry}
          material={materials.DefaultMaterial}
          position={[2.108, 0.782, -4.39]}
          scale={[0.576, 0.689, 0.576]}
        />
        <group name="Circle" position={[3.57, 0.693, -2.822]} scale={0.355}>
          <mesh
            name="Circle_1"
            castShadow
            receiveShadow
            geometry={nodes.Circle_1.geometry}
            material={materials.Plant_Pot}
          />
          <mesh
            name="Circle_2"
            castShadow
            receiveShadow
            geometry={nodes.Circle_2.geometry}
            material={materials["White murble"]}
          />
        </group>
        <mesh
          name="IVY_Curve004"
          castShadow
          receiveShadow
          geometry={nodes.IVY_Curve004.geometry}
          material={materials.Plant_Stem}
          position={[3.383, 0.85, -2.58]}
          scale={0.597}
        />
        <mesh
          name="Plane005"
          castShadow
          receiveShadow
          geometry={nodes.Plane005.geometry}
          material={materials.Plant_Leaf}
          position={[3.366, 0.857, -2.69]}
          scale={0.741}
        />
        <mesh
          name="Circle002"
          castShadow
          receiveShadow
          geometry={nodes.Circle002.geometry}
          material={materials.BlackPlastic}
          position={[1.345, 1.249, 1.804]}
          scale={0.1}
        />
        <group name="Circle005" position={[1.345, 1.249, 1.804]} scale={0.099}>
          <mesh
            name="Circle043"
            castShadow
            receiveShadow
            geometry={nodes.Circle043.geometry}
            material={materials.BlackPlastic}
          />
          <mesh
            name="Circle043_1"
            castShadow
            receiveShadow
            geometry={nodes.Circle043_1.geometry}
            material={materials.Plant_Leaf}
          />
          <mesh
            name="Circle043_2"
            castShadow
            receiveShadow
            geometry={nodes.Circle043_2.geometry}
            material={materials["Material.006"]}
          />
        </group>
        <mesh
          name="Circle006"
          castShadow
          receiveShadow
          geometry={nodes.Circle006.geometry}
          material={materials.BlackLeazer}
          position={[1.284, 1.253, 1.804]}
          scale={0.083}
        />
        <mesh
          name="Circle007"
          castShadow
          receiveShadow
          geometry={nodes.Circle007.geometry}
          material={materials.Metal}
          position={[1.364, 1.238, 1.899]}
          scale={0.013}
        />
        <mesh
          name="Circle018"
          castShadow
          receiveShadow
          geometry={nodes.Circle018.geometry}
          material={materials.BlackPlastic}
          position={[1.282, 1.254, 1.726]}
          scale={0.041}
        />
        <mesh
          name="Circle019"
          castShadow
          receiveShadow
          geometry={nodes.Circle019.geometry}
          material={materials.BlackPlastic}
          position={[1.282, 1.254, 1.882]}
          scale={0.041}
        />
        <mesh
          name="Circle048"
          castShadow
          receiveShadow
          geometry={nodes.Circle048.geometry}
          material={materials["Material.001"]}
          position={[1.283, 1.254, 1.877]}
          scale={0.042}
        />
        <mesh
          name="Circle049"
          castShadow
          receiveShadow
          geometry={nodes.Circle049.geometry}
          material={materials["Material.001"]}
          position={[1.283, 1.254, 1.731]}
          scale={0.042}
        />
        <group name="ram" position={[-0.215, 0.508, -4.628]}>
          <group name="dvere" position={[0.008, 1.018, 0.066]} scale={1.013}>
            <mesh
              name="Cube007_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube007_1.geometry}
              material={materials.wood}
            />
            <mesh
              name="Cube007_2"
              castShadow
              receiveShadow
              geometry={nodes.Cube007_2.geometry}
              material={materials.stainless}
            />
            <mesh
              name="Cube007_3"
              castShadow
              receiveShadow
              geometry={nodes.Cube007_3.geometry}
              material={materials.black}
            />
          </group>
          <group position={[0, 1.041, -0.001]} scale={1.04}>
            <mesh
              name="Cube005_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube005_1.geometry}
              material={materials.wood}
            />
            <mesh
              name="Cube005_2"
              castShadow
              receiveShadow
              geometry={nodes.Cube005_2.geometry}
              material={materials.stainless}
            />
          </group>
        </group>
        <group
          name="Cube1409"
          position={[3.374, 0.776, 1.6]}
          rotation={[-Math.PI, 0, 1.577]}
          scale={1.726}
        >
          <mesh
            name="Cube1403"
            castShadow
            receiveShadow
            geometry={nodes.Cube1403.geometry}
            material={materials["Iron Touched"]}
            position={[0, 0.015, 0]}
            scale={0.007}
          />
          <mesh
            name="Cube1404"
            castShadow
            receiveShadow
            geometry={nodes.Cube1404.geometry}
            material={materials["plastic touched"]}
            position={[0, 0.015, 0]}
            scale={0.007}
          />
          <mesh
            name="Cube1405"
            castShadow
            receiveShadow
            geometry={nodes.Cube1405.geometry}
            material={materials["Brass polished"]}
            position={[0.001, 0.016, 0]}
            scale={0.006}
          />
          <mesh
            name="Cube1406"
            castShadow
            receiveShadow
            geometry={nodes.Cube1406.geometry}
            material={materials["Brass polished"]}
            position={[0.004, 0.016, 0]}
            scale={0.006}
          />
          <mesh
            name="Cube1407"
            castShadow
            receiveShadow
            geometry={nodes.Cube1407.geometry}
            material={materials["Brass polished"]}
            position={[-0.001, 0.016, 0]}
            scale={0.006}
          />
          <mesh
            name="Cube1408"
            castShadow
            receiveShadow
            geometry={nodes.Cube1408.geometry}
            material={materials["Brass polished"]}
            position={[-0.004, 0.016, 0]}
            scale={0.006}
          />
          <mesh
            name="NurbsCurve"
            castShadow
            receiveShadow
            geometry={nodes.NurbsCurve.geometry}
            material={materials.heater_black}
            position={[-0.146, -0.038, 0.101]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={0.147}
          />
          <mesh
            name="Cube011_1_instance_0"
            castShadow
            receiveShadow
            geometry={nodes.Cube011_1_instance_0.geometry}
            material={materials["black rubber.002"]}
            position={[0, -0.008, 0]}
            scale={0.016}
          />
        </group>
        <group
          name="Cube1416"
          position={[3.203, 1.281, 1.232]}
          rotation={[0, -Math.PI / 6, 1.577]}
          scale={1.726}
        >
          <mesh
            name="Cube1410"
            castShadow
            receiveShadow
            geometry={nodes.Cube1410.geometry}
            material={materials["Iron Touched"]}
            position={[0, 0.015, 0]}
            scale={0.007}
          />
          <mesh
            name="Cube1411"
            castShadow
            receiveShadow
            geometry={nodes.Cube1411.geometry}
            material={materials["plastic touched"]}
            position={[0, 0.015, 0]}
            scale={0.007}
          />
          <mesh
            name="Cube1412"
            castShadow
            receiveShadow
            geometry={nodes.Cube1412.geometry}
            material={materials["Brass polished"]}
            position={[0.001, 0.016, 0]}
            scale={0.006}
          />
          <mesh
            name="Cube1413"
            castShadow
            receiveShadow
            geometry={nodes.Cube1413.geometry}
            material={materials["Brass polished"]}
            position={[0.004, 0.016, 0]}
            scale={0.006}
          />
          <mesh
            name="Cube1414"
            castShadow
            receiveShadow
            geometry={nodes.Cube1414.geometry}
            material={materials["Brass polished"]}
            position={[-0.001, 0.016, 0]}
            scale={0.006}
          />
          <mesh
            name="Cube1415"
            castShadow
            receiveShadow
            geometry={nodes.Cube1415.geometry}
            material={materials["Brass polished"]}
            position={[-0.004, 0.016, 0]}
            scale={0.006}
          />
          <mesh
            name="Cube011_1_instance_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube011_1_instance_1.geometry}
            material={materials["black rubber.002"]}
            position={[0, -0.008, 0]}
            scale={0.016}
          />
        </group>
        <group
          name="Cube001"
          position={[3.245, 1.284, -0.588]}
          rotation={[0.004, 0.492, 1.581]}
          scale={1.726}
        >
          <mesh
            name="Cube002"
            castShadow
            receiveShadow
            geometry={nodes.Cube002.geometry}
            material={materials["Brass polished"]}
            position={[-0.004, 0.016, 0]}
            scale={0.006}
          />
          <mesh
            name="Cube003"
            castShadow
            receiveShadow
            geometry={nodes.Cube003.geometry}
            material={materials["Brass polished"]}
            position={[-0.001, 0.016, 0]}
            scale={0.006}
          />
          <mesh
            name="Cube004"
            castShadow
            receiveShadow
            geometry={nodes.Cube004.geometry}
            material={materials["Brass polished"]}
            position={[0.004, 0.016, 0]}
            scale={0.006}
          />
          <mesh
            name="Cube005"
            castShadow
            receiveShadow
            geometry={nodes.Cube005.geometry}
            material={materials["Brass polished"]}
            position={[0.001, 0.016, 0]}
            scale={0.006}
          />
          <mesh
            name="Cube006"
            castShadow
            receiveShadow
            geometry={nodes.Cube006.geometry}
            material={materials["plastic touched"]}
            position={[0, 0.015, 0]}
            scale={0.007}
          />
          <mesh
            name="Cube007"
            castShadow
            receiveShadow
            geometry={nodes.Cube007.geometry}
            material={materials["Iron Touched"]}
            position={[0, 0.015, 0]}
            scale={0.007}
          />
          <mesh
            name="Cube011_1_instance_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube011_1_instance_2.geometry}
            material={materials["black rubber.002"]}
            position={[0, -0.008, 0]}
            scale={0.016}
          />
        </group>
        <mesh
          name="Cube009"
          castShadow
          receiveShadow
          geometry={nodes.Cube009.geometry}
          material={materials["Brass polished"]}
          position={[3.345, 0.782, 1.581]}
          scale={0.01}
        />
        <mesh
          name="Cube010"
          castShadow
          receiveShadow
          geometry={nodes.Cube010.geometry}
          material={materials["Brass polished"]}
          position={[3.345, 0.778, 1.581]}
          scale={0.01}
        />
        <mesh
          name="Cube011"
          castShadow
          receiveShadow
          geometry={nodes.Cube011.geometry}
          material={materials["Brass polished"]}
          position={[3.345, 0.77, 1.581]}
          scale={0.01}
        />
        <mesh
          name="Cube012"
          castShadow
          receiveShadow
          geometry={nodes.Cube012.geometry}
          material={materials["Brass polished"]}
          position={[3.345, 0.774, 1.581]}
          scale={0.01}
        />
        <mesh
          name="Cube013"
          castShadow
          receiveShadow
          geometry={nodes.Cube013.geometry}
          material={materials["plastic touched"]}
          position={[3.348, 0.776, 1.582]}
          scale={0.013}
        />
        <mesh
          name="Cube014"
          castShadow
          receiveShadow
          geometry={nodes.Cube014.geometry}
          material={materials["Iron Touched"]}
          position={[3.348, 0.776, 1.582]}
          scale={0.013}
        />
        <mesh
          name="NurbsCurve001"
          castShadow
          receiveShadow
          geometry={nodes.NurbsCurve001.geometry}
          material={materials.heater_black}
          position={[3.439, 1.028, 1.408]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
          scale={0.254}
        />
        <mesh
          name="Cube048"
          castShadow
          receiveShadow
          geometry={nodes.Cube048.geometry}
          material={materials["black rubber.002"]}
          position={[3.387, 0.776, 1.582]}
          scale={0.028}
        />
        <mesh
          name="Black_keys_1"
          castShadow
          receiveShadow
          geometry={nodes.Black_keys_1.geometry}
          material={materials["Black Keys"]}
          position={[1.77, 1.266, 1.862]}
          scale={0.049}
        />
        <mesh
          name="Black_keys_2"
          castShadow
          receiveShadow
          geometry={nodes.Black_keys_2.geometry}
          material={materials["Black Keys"]}
          position={[1.728, 1.266, 1.774]}
          scale={0.055}
        />
        <mesh
          name="Black_keys_3"
          castShadow
          receiveShadow
          geometry={nodes.Black_keys_3.geometry}
          material={materials["Black Keys"]}
          position={[1.685, 1.266, 1.686]}
          scale={0.049}
        />
        <mesh
          name="Black_keys_4"
          castShadow
          receiveShadow
          geometry={nodes.Black_keys_4.geometry}
          material={materials["Black Keys"]}
          position={[1.643, 1.266, 1.598]}
          scale={0.055}
        />
        <mesh
          name="Cube033"
          castShadow
          receiveShadow
          geometry={nodes.Cube033.geometry}
          material={materials["Black case"]}
          position={[1.758, 1.238, 1.675]}
          scale={0.201}
        />
        <mesh
          name="White_keys"
          castShadow
          receiveShadow
          geometry={nodes.White_keys.geometry}
          material={materials["White keys"]}
          position={[1.709, 1.251, 1.705]}
          scale={0.217}
        />
        <group position={[1.655, 1.244, 1.731]} scale={0.266}>
          <mesh
            name="Cube035_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube035_1.geometry}
            material={materials["Red case"]}
          />
          <mesh
            name="Cube035_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube035_2.geometry}
            material={materials["Black case"]}
          />
          <mesh
            name="Cube035_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube035_3.geometry}
            material={materials["LED red"]}
          />
          <mesh
            name="Cube035_4"
            castShadow
            receiveShadow
            geometry={nodes.Cube035_4.geometry}
            material={materials["Metal Switch"]}
          />
          <mesh
            name="Cube035_5"
            castShadow
            receiveShadow
            geometry={nodes.Cube035_5.geometry}
            material={materials["LED white"]}
          />
        </group>
      </motion.group>
    </group>
  );
}

useGLTF.preload("/models/studio.glb");
